import React, { useState } from 'react';
import { Image as ImageIcon, Loader2, Sparkles, Zap } from 'lucide-react';
import { generateMarketMoodImage, ChatContext } from '../services/geminiService';

interface VisualizerProps {
  context: ChatContext;
}

const Visualizer: React.FC<VisualizerProps> = ({ context }) => {
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [resolution, setResolution] = useState<'1K' | '2K' | '4K'>('1K');
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const url = await generateMarketMoodImage(context, resolution);
      if (url) {
        setImageUrl(url);
      } else {
        setError("Failed to generate image. Try again.");
      }
    } catch (e) {
      setError("Error calling Gemini API.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-zinc-900/50 backdrop-blur-md rounded-2xl shadow-xl border border-white/5 p-6 flex flex-col h-full relative overflow-hidden">
      {/* Decorative gradient */}
      <div className="absolute top-0 right-0 w-32 h-32 bg-purple-500/10 blur-3xl rounded-full -mr-10 -mt-10 pointer-events-none" />

      <div className="flex items-center gap-2 mb-4 relative z-10">
        <Zap className="text-yellow-400 fill-yellow-400/20" size={20} />
        <h3 className="font-semibold text-zinc-100">Market Mood Visualizer</h3>
      </div>
      
      <div className="flex-1 bg-black/40 rounded-xl border border-white/5 flex items-center justify-center overflow-hidden relative min-h-[300px] group transition-all hover:border-white/10">
        {loading ? (
          <div className="text-center">
            <div className="relative">
                <div className="absolute inset-0 bg-cyan-500 blur-xl opacity-20 animate-pulse"></div>
                <Loader2 className="animate-spin h-10 w-10 text-cyan-400 mx-auto mb-4 relative z-10" />
            </div>
            <p className="text-zinc-400 text-sm font-medium">Dreaming of market patterns...</p>
          </div>
        ) : imageUrl ? (
          <div className="relative w-full h-full">
             <img src={imageUrl} alt="Market Mood" className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-105" />
             <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-4">
                 <p className="text-white text-xs font-medium">Generated by Gemini 3 Pro</p>
             </div>
          </div>
        ) : (
          <div className="text-center p-8 max-w-xs">
            <div className="bg-zinc-800/50 inline-flex p-5 rounded-2xl mb-4 border border-white/5 shadow-inner">
              <ImageIcon className="text-zinc-600 h-10 w-10" />
            </div>
            <p className="text-zinc-500 text-sm">Generate an abstract cinematic representation of the current technical sentiment.</p>
          </div>
        )}
        
        {/* Quality Badge Overlay */}
        {imageUrl && (
            <div className="absolute top-3 right-3 bg-black/40 backdrop-blur-md px-2 py-1 rounded text-[10px] text-white font-mono border border-white/10 shadow-lg">
                {resolution}
            </div>
        )}
      </div>

      <div className="mt-5 flex items-center justify-between gap-4 relative z-10">
        <div className="flex items-center gap-1 bg-black/40 rounded-lg p-1 border border-white/5">
             {(['1K', '2K', '4K'] as const).map(res => (
                 <button
                    key={res}
                    onClick={() => setResolution(res)}
                    className={`px-3 py-1.5 text-[10px] font-bold rounded-md transition-all ${resolution === res ? 'bg-zinc-700 text-white shadow' : 'text-zinc-500 hover:text-zinc-300'}`}
                 >
                     {res}
                 </button>
             ))}
        </div>
        <button
          onClick={handleGenerate}
          disabled={loading}
          className="bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white px-5 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition-all shadow-lg shadow-purple-900/20 disabled:opacity-50 disabled:cursor-not-allowed hover:shadow-purple-500/20 hover:-translate-y-0.5"
        >
          <Sparkles size={16} />
          {imageUrl ? 'Regenerate' : 'Generate'}
        </button>
      </div>
      {error && <p className="text-red-400 text-xs mt-3 text-center bg-red-900/20 py-1 rounded border border-red-900/30">{error}</p>}
    </div>
  );
};

export default Visualizer;